# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\x13\x61\x32\x61.controlplane.v1\"\x95\x01\n\x0e\x43ontrolMessage\x12\x36\n\x0b\x63\x61ncel_task\x18\x01 \x01(\x0b\x32\x1f.a2a.controlplane.v1.CancelTaskH\x00\x12@\n\x10heartbeat_config\x18\x02 \x01(\x0b\x32$.a2a.controlplane.v1.HeartbeatConfigH\x00\x42\t\n\x07\x63ommand\"-\n\nCancelTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"]\n\x0fHeartbeatConfig\x12\x18\n\x10\x62\x61se_interval_ms\x18\x01 \x01(\r\x12\x17\n\x0fmax_interval_ms\x18\x02 \x01(\r\x12\x17\n\x0fmiss_multiplier\x18\x03 \x01(\rBy\n%io.github.devrbhub.a2acontrolplane.v1P\x01Z8github.com/dev-rb-hub/a2a-control-plane/schemas/v1;a2av1\xaa\x02\x13\x41\x32\x41.ControlPlane.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%io.github.devrbhub.a2acontrolplane.v1P\001Z8github.com/dev-rb-hub/a2a-control-plane/schemas/v1;a2av1\252\002\023A2A.ControlPlane.V1'
  _globals['_CONTROLMESSAGE']._serialized_start=39
  _globals['_CONTROLMESSAGE']._serialized_end=188
  _globals['_CANCELTASK']._serialized_start=190
  _globals['_CANCELTASK']._serialized_end=235
  _globals['_HEARTBEATCONFIG']._serialized_start=237
  _globals['_HEARTBEATCONFIG']._serialized_end=330
# @@protoc_insertion_point(module_scope)
